"""
Django settings for blissme_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-change-this-in-production-xyz789'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['54.79.9.184',
                  '*',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'fragrances',
    'django.contrib.sitemaps',
]

# Security middleware - fixed configuration
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blissme_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blissme_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings
DEFAULT_FROM_EMAIL = 'victnowreach@gmail.com'
ADMIN_EMAIL = 'victnowreach@gmail.com'

# Fast2SMS Configuration (requires payment first)
FAST2SMS_API_KEY = 'buN1BkI57lcxVrSmjvKHYozaiwCsgZ6nGXfQAT3O8UE4Ly2dhMEHxfPwJSm3byt6M2gdl0TIpDQaGk5U'
FAST2SMS_SENDER_ID = 'FSTSMS'
FAST2SMS_ROUTE = '3'  # Transactional route
FAST2SMS_LANGUAGE = 'english'

# TextLocal Configuration (free trial available)
TEXTLOCAL_API_KEY = 'your_textlocal_api_key_here'
TEXTLOCAL_SENDER = 'TXTLCL'

# CORS and CSRF settings for proxy
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://machinelike-unsentimentally-cherry.ngrok-free.dev",
    "https://*.ngrok-free.dev",
    "https://*.ngrok.io",
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://machinelike-unsentimentally-cherry.ngrok-free.dev",
    "https://*.ngrok-free.dev",
    "https://*.ngrok.io",
]

# CSRF Cookie Settings for Admin Panel
CSRF_COOKIE_SECURE = False  # Set to False for development
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to False for development
SESSION_COOKIE_SAMESITE = 'Lax'

# Razorpay Payment Configuration
RAZORPAY_KEY_ID = 'rzp_test_1DP5mmOlF5G1ag'  # Test Key - Replace with production key
RAZORPAY_KEY_SECRET = 'test_secret_key_placeholder'  # Test Secret - Replace with actual key

# For Production, use your actual Razorpay credentials:
# RAZORPAY_KEY_ID = 'rzp_live_your_actual_key_id'
# RAZORPAY_KEY_SECRET = 'your_actual_secret_key'

# Razorpay Webhook Secret (for payment notifications)
RAZORPAY_WEBHOOK_SECRET = 'your_webhook_secret'

# Payment Settings
PAYMENT_AMOUNT = 249900  # ₹2,499 in paise
PAYMENT_CURRENCY = 'INR'
PAYMENT_CAPTURE = 1  # Auto-capture payments

# Messages framework
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom login URL
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
