# Generated by Django 4.2.16 on 2026-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('50ml', '50ml'), ('100ml', '100ml'), ('30ml', '30ml')], default='50ml', max_length=10),
        ),
    ]
