# Generated by Django 4.2.16 on 2026-02-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0006_remove_corporateorder_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('trial_pack_name', models.CharField(default='VICTNOW Trial Pack', max_length=200)),
                ('trial_pack_description', models.TextField(default='VICTNOW MUSE, VICTNOW NEXUS, VICTNOW FORGE - 5ML each')),
                ('amount', models.DecimalField(decimal_places=2, default=29.99, max_digits=10)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('wallet', 'Digital Wallet')], default='upi', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trial Pack Order',
                'verbose_name_plural': 'Trial Pack Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
