# Generated by Django 4.2.16 on 2026-02-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0007_trialpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialPackTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, choices=[('delhivery', 'Delhivery'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('bluedart', 'Blue Dart'), ('xpressbees', 'Xpressbees'), ('ekart', 'Ekart'), ('india_post', 'India Post'), ('other', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='ordered', max_length=20)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('tracking_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='fragrances.trialpack')),
            ],
            options={
                'verbose_name': 'Trial Pack Tracking',
                'verbose_name_plural': 'Trial Pack Tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
