# Generated by Django 4.2.16 on 2026-02-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0010_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_segment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_since',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_purchase_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marketing_consent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_fragrance_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_price_range',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_purchases',
        ),
    ]
