# Generated by Django 5.2.7 on 2026-03-28 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0011_remove_userprofile_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trialpack',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('order_created', 'Order Created'), ('trial_pack_created', 'Trial Pack Created'), ('corporate_order_created', 'Corporate Order Created'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('product_viewed', 'Product Viewed'), ('cart_updated', 'Cart Updated'), ('payment_completed', 'Payment Completed'), ('review_submitted', 'Review Submitted'), ('contact_submitted', 'Contact Form Submitted')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'Order', 'TrialPack')", max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of related object', max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional activity data as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fragrances__user_id_3789f9_idx'), models.Index(fields=['activity_type', '-created_at'], name='fragrances__activit_3624b7_idx')],
            },
        ),
    ]
