# Generated by Django 5.2.7 on 2026-04-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Number of items in stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('limited', 'Limited Stock')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trialpack',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2499.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_method',
            field=models.CharField(choices=[('mobile', 'Mobile OTP'), ('google', 'Google OAuth'), ('facebook', 'Facebook OAuth'), ('standard', 'Standard Registration')], default='mobile', max_length=20),
        ),
    ]
