# Generated by Django 5.2.7 on 2026-04-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0019_alter_userprofile_is_verified_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_browser',
            field=models.CharField(blank=True, help_text='Browser used for registration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_device_type',
            field=models.CharField(blank=True, help_text='Device type used for registration', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which user registered', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_location',
            field=models.CharField(blank=True, help_text='Location from which user registered', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_user_agent',
            field=models.TextField(blank=True, help_text='Browser/device information from registration', null=True),
        ),
    ]
