# Generated by Django 4.2.16 on 2026-02-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0003_product_category_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fragrance_type', models.CharField(choices=[('victnow_forge', 'VICTNOW FORGE'), ('victnow_muse', 'VICTNOW MUSE'), ('victnow_nexus', 'VICTNOW NEXUS'), ('mixed', 'Mixed Collection')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
