# Generated by Django 4.2.16 on 2026-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0005_userprofile_ordertracking_bulkordertracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateorder',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='corporateorder',
            name='special_requirements',
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='packaging',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Box'), ('premium', 'Premium Gift Box'), ('custom', 'Custom Branding')], default='standard', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='packaging_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=2999.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='corporateorder',
            name='unit_size',
            field=models.CharField(blank=True, choices=[('50ml', '50ml'), ('100ml', '100ml'), ('custom', 'Custom Size')], default='50ml', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='corporateorder',
            name='fragrance_type',
            field=models.CharField(choices=[('victnow_forge', 'VICTNOW FORGE'), ('victnow_muse', 'VICTNOW MUSE'), ('victnow_nexus', 'VICTNOW NEXUS'), ('mixed_collection', 'Mixed Collection'), ('custom', 'Custom Mix')], max_length=20),
        ),
    ]
