# Generated by Django 4.2.16 on 2026-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0008_trialpacktracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='frontend_session_id',
            field=models.CharField(blank=True, help_text='Frontend session identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of login attempts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_browser',
            field=models.CharField(blank=True, help_text='Browser used for login', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_device_type',
            field=models.CharField(blank=True, help_text='Device type (mobile, desktop, tablet)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which user logged in', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_location',
            field=models.CharField(blank=True, help_text='Location from which user logged in', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_user_agent',
            field=models.TextField(blank=True, help_text='Browser/device information from login', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='successful_logins',
            field=models.PositiveIntegerField(default=0, help_text='Number of successful logins'),
        ),
    ]
