# Generated by Django 4.2.16 on 2026-02-18 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0009_userprofile_frontend_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Address line 1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Address line 2', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annual_income',
            field=models.CharField(blank=True, help_text='Annual income range', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name if applicable', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='India', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_segment',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], default='individual', help_text='Customer segment', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_since',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Customer since date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Customer date of birth', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], help_text='Education level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Customer gender', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Last purchase date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty points balance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], help_text='Marital status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_consent',
            field=models.BooleanField(default=True, help_text='Consent for marketing communications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_subscription',
            field=models.BooleanField(default=True, help_text='Newsletter subscription status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, help_text='Customer occupation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_fragrance_type',
            field=models.CharField(blank=True, choices=[('floral', 'Floral'), ('woody', 'Woody'), ('citrus', 'Citrus'), ('oriental', 'Oriental'), ('fresh', 'Fresh'), ('sweet', 'Sweet'), ('spicy', 'Spicy')], help_text='Preferred fragrance type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_price_range',
            field=models.CharField(blank=True, choices=[('budget', 'Budget (Under ₹1000)'), ('mid_range', 'Mid Range (₹1000-₹5000)'), ('premium', 'Premium (₹5000-₹10000)'), ('luxury', 'Luxury (Over ₹10000)')], help_text='Preferred price range', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total purchase amount', max_digits=10),
        ),
    ]
